import {
  AlertCircle,
  Bell,
  BookOpen,
  Calendar,
  CheckCircle,
  Flag,
  Gift,
  Globe,
  GraduationCap,
  HandHeart,
  Heart,
  Info,
  Lightbulb,
  Mail,
  Megaphone,
  MessageCircle,
  PartyPopper,
  Rocket,
  Shield,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  Trophy,
  Users,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { CalloutIconKey } from "./schema";

/** Maps a stored icon key to its `lucide-react` component. */
export const CALLOUT_ICONS: Record<CalloutIconKey, LucideIcon> = {
  megaphone: Megaphone,
  sparkles: Sparkles,
  rocket: Rocket,
  star: Star,
  heart: Heart,
  "hand-heart": HandHeart,
  info: Info,
  bell: Bell,
  gift: Gift,
  party: PartyPopper,
  flag: Flag,
  zap: Zap,
  check: CheckCircle,
  alert: AlertCircle,
  "thumbs-up": ThumbsUp,
  users: Users,
  calendar: Calendar,
  mail: Mail,
  message: MessageCircle,
  book: BookOpen,
  graduation: GraduationCap,
  target: Target,
  trophy: Trophy,
  lightbulb: Lightbulb,
  shield: Shield,
  globe: Globe,
};
